name: fleet

services:
    backend:
        image: fleet/backend
        container_name: fleet-backend
        build:
            context: ./src/backend
        ports:
            - "3000:80"
        tty: true
        stdin_open: true
        environment:
            - USERNAME=???
            - PASSWORD=???
        volumes:
            - /app/node_modules
            - ./src/backend/code:/app/code

    babel:
        depends_on:
            - "backend"
        image: fleet/babel
        container_name: fleet-babel
        build:
            context: ./src/babel
        ports:
            - "9000:80"
        tty: true
        stdin_open: true
        environment:
            - USERNAME=???
            - PASSWORD=???
        volumes:
            - /app/node_modules
            - ./src/babel/code:/app/code

    # webapp:
    #     depends_on:
    #         - "backend"
    #     image: fleet/webapp
    #     container_name: fleet-webapp
    #     build:
    #         context: ./src/webapp
    #     ports:
    #         - "9002:3000"
    #     tty: true
    #     stdin_open: true
    #     environment:
    #         - USERNAME=???
    #         - PASSWORD=???
    #     volumes:
    #         - /app/node_modules
    #         - ./src/webapp/code:/app/src
    #         - ./src/webapp/public:/app/public
        