name: fleetco

services:
    backend:
        image: fleetco/backend
        container_name: fleetco-backend
        build:
            context: ./src/backend
        ports:
            - "3000:80"
        tty: true
        stdin_open: true
        environment:
            - USERNAME=???
            - PASSWORD=???
        volumes:
            - /app/node_modules
            - ./src/backend/code:/app/code

    webapp:
        depends_on:
            - "backend"
        image: fleetco/webapp
        container_name: fleetco-webapp
        build:
            context: ./src/webapp
        ports:
            - "9002:3000"
        tty: true
        stdin_open: true
        environment:
            - USERNAME=???
            - PASSWORD=???
        volumes:
            - /app/node_modules
            - ./src/webapp/code:/app/src
            - ./src/webapp/public:/app/public
        