name: fleet

services:
    backend:
        image: fleet/backend
        container_name: fleet-backend
        build:
            context: ./src/backend
        ports:
            - "3000:80"
        tty: true
        stdin_open: true
        environment:
            - USERNAME=???
            - PASSWORD=???
        volumes:
            - /app/node_modules
            - ./src/backend/code:/app/code

    babel:
        depends_on:
            - "backend"
        image: fleet/babel
        container_name: fleet-babel
        build:
            context: ./src/babel
        ports:
            - "8081:80"
        tty: true
        stdin_open: true
        environment:
            - USERNAME=???
            - PASSWORD=???
        volumes:
            - /app/node_modules
            - ./src/babel/code:/app/code
